//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeLibraryApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class booksRead
    {
        public int BooksRead_id { get; set; }
        public int Book_id { get; set; }
        public int Reader_id { get; set; }
        public System.DateTime DateRead { get; set; }
    
        public virtual book book { get; set; }
        public virtual reader reader { get; set; }
    }
}
